DATA:
  img_dir: '/media/seven/7EF450DF596F8A46/data/fer_data/RAF-DB/basic/Image/aligned'
  train_label_path: '/media/seven/7EF450DF596F8A46/data/fer_data/RAF-DB/basic/EmoLabel/list_patition_label.txt'
  val_label_path: '/media/seven/7EF450DF596F8A46/data/fer_data/RAF-DB/basic/EmoLabel/list_patition_label.txt'
  dataset_type: 'RAF_DB'
  input_size: 90  # 224
  input_channel: 1
TRAIN:
  save_dir: '/media/seven/7EF450DF596F8A46/weights/fer/raf-db/gcn/'
  batch_size: 64
  num_train_epochs: 150

  optimizer: 'sgd'
  warmup_steps: 200
  learning_rate: 1e-3  # 2e-3 #0.001  # 1e-4
  momentum: 0.9
  milestones: [2000, 4000]
  lr_decay_gamma: 0.9
  adam_epsilon: 1e-5
  early_stop_n: 150
  drop_rate: 0
  weight_decay: 3e-04 # 1e-5 #1e-4    # TODO. study later.

  learner: 'simple'  # 'scn' 
  beta: 0.7
  relabel_epoch: 10
  margin_1: 0.15
  margin_2: 0.2

MODEL:
  model_name: 'gcn'
  num_classes: 7
  pretrained: ''  # '/media/yz/62C9BA4E5D826344/pretrained_model/ijba_res18_naive.pth.tar'
  # pretrained: '/media/yz/62C9BA4E5D826344/pretrained_model/resnet18_110.pth'
  checkpoint: ''


LOSS:
  type: "CE" #'CE'  # or 'CE_WLS'
  alpha: 0.0125  # on use if only ce
  use_label_smooth: False
  use_update_w: False

SYSTEM:
  NUM_WORKERS: 0
