DATA:
  img_dir: '/media/yz/62C9BA4E5D826344/data/RAF-DB/basic/Image/aligned'
  train_label_path: '/media/yz/62C9BA4E5D826344/data/RAF-DB/basic/EmoLabel/list_patition_label.txt'
  val_label_path: '/media/yz/62C9BA4E5D826344/data/RAF-DB/basic/EmoLabel/list_patition_label.txt'
  dataset_type: 'RAF_DB'

TRAIN:
  save_dir: '/media/yz/62C9BA4E5D826344/weights/fer/raf_db/scn/ce/'
  batch_size: 600
  num_train_epochs: 300

  optimizer: 'rmsprop' #'sgd' #'adam'
  warmup_steps: 200
  learning_rate: 0.0001  #0.01
  momentum: 0.0 #0.9
  milestones: [2000, 4000]
  lr_decay_gamma: 0.2
  adam_epsilon: 1e-5
  early_stop_n: 300
  drop_rate: 0
  weight_decay: 1e-5 #1e-4    # TODO. study later.


  use_scn_group: True
  beta: 0.7
  relabel_epoch: 10
  margin_1: 0.15
  margin_2: 0.2

MODEL:
  model_name: 'scn_res18'
  num_classes: 7
  pretrained: '/media/yz/62C9BA4E5D826344/pretrained_model/ijba_res18_naive.pth.tar'
  checkpoint: ''


LOSS:
  type: 'CE_WLS'  # or 'CE_WLS'
  alpha: [0.0125, 0.5, 0.75, 1.0]  # on use if only ce
  use_update_w: True
  update_w_start_epoch: 0
  use_label_smooth: False

SYSTEM:
  NUM_WORKERS: 0
